version: 2

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .

# explicit set the os to build and python version
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
# spot sphinx warnings
sphinx:
  fail_on_warning: true
# build PDF and EPUB
formats:
  - pdf
  - epub
